import { test, expect } from '@playwright/test';

test('PersonaJuridica', async ({ page }) => {
  await page.goto('https://abt.bits.bo/auth/login');
  await page.getByRole('button', { name: 'INGRESAR COMO FUNCIONARIO' }).click();
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).click();
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).click();
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).fill('admin');
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Admin1234');
  await page.getByRole('button', { name: 'INICIAR SESIÓN' }).click();
  await page.locator('a').filter({ hasText: 'Usuarios Forestales' }).click();
  await page.locator('a').filter({ hasText: 'Administración de Agentes' }).click();
  await page.getByRole('link', { name: ' Reinscripciones' }).click();
  await page.getByRole('row', { name: '25/06/2025 16:40 Sin Número' }).locator('app-auxiliar-officers-options').getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Enviar evalaluación técnica' }).locator('a').click();
  await page.getByRole('button', { name: 'Enviar' }).click();
  //await page.getByRole('button', { name: 'Enviar' }).click();
  await page.getByText('El usuario no tiene un').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Cancelar' }).click();
  //await page.getByRole('row', { name: '25/06/2025 16:40 Sin Número' }).locator('app-auxiliar-officers-options').getByRole('button').click();
  await page.getByRole('tab', { name: ' Persona Jurídica' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Aprobadas' }).click();
  await page.getByRole('tab', { name: ' Persona Natural' }).click();
  await page.locator('app-auxiliar-officers-options').getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Enviar resolución' }).locator('a').click();
  await page.getByRole('button', { name: 'Enviar' }).click();
  await page.getByRole('tab', { name: ' Persona Jurídica' }).click();
  await page.getByRole('radio', { name: 'Inscripciones en Revisión' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Aprobadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Observadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Deshabilitadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Observadas' }).click();
  await page.getByRole('tab', { name: ' Persona Natural' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Aprobadas' }).click();
  await page.locator('app-auxiliar-officers-options').getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Enviar resolución' }).locator('a').click();
  await page.getByRole('button', { name: 'Enviar' }).click();
  await page.getByRole('tab', { name: ' Persona Jurídica' }).click();
  await page.getByRole('tab', { name: ' Persona Natural' }).click();
  await page.getByRole('radio', { name: 'Inscripciones en Revisión' }).click();
  await page.getByRole('row', { name: '25/06/2025 16:40 Sin Número' }).locator('app-auxiliar-officers-options').getByRole('button').click();
  await page.getByText('pepe Lopez').click();
  await page.getByText('pepe Lopez').click();
  await page.getByRole('row', { name: '25/06/2025 16:40 Sin Número' }).locator('app-auxiliar-officers-options').getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Revisar pago' }).locator('a').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('row', { name: '25/06/2025 16:40 Sin Número' }).locator('app-auxiliar-officers-options').getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Revisar pago' }).locator('a').click();
  await page.getByRole('textbox', { name: 'Escribe una observación si' }).click();
  await page.getByRole('textbox', { name: 'Escribe una observación si' }).fill('pago realizado');
  await page.getByRole('button', { name: '' }).click();
  await page.getByText('El registro ha sido').click();
  await page.getByRole('alert').getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'AM' }).click();
  await page.getByRole('button', { name: ' Cerrar Sesión' }).click();
});