import { test, expect } from '@playwright/test';

test('Recorrido_UsuariosForestales', async ({ page }) => {
  await page.goto('https://abt.bits.bo/auth/login');
  await page.getByRole('button', { name: 'INGRESAR COMO FUNCIONARIO' }).click();
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).click();
  await page.getByRole('textbox', { name: 'Correo Electronico o Usuario' }).fill('admin');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Admin1234');
  await page.getByRole('button', { name: 'INICIAR SESIÓN' }).click();
  await page.locator('a').filter({ hasText: 'Usuarios Forestales' }).click();
  await page.locator('a').filter({ hasText: 'Administración de Agentes' }).click();
  await page.getByRole('link', { name: ' Inscripciones' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Aprobadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Observadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Deshabilitadas' }).click();
  await page.getByRole('radio', { name: '' }).click();
  await page.getByRole('radio', { name: '' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Observadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Aprobadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones en Revisión' }).click();
  await page.getByRole('button', { name: ' Actualizar' }).click();
  await page.getByRole('tab', { name: ' Persona Jurídica' }).click();
  await page.getByRole('tab', { name: ' Persona Natural' }).click();
  await page.getByRole('link', { name: ' Reinscripciones' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Aprobadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Observadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Deshabilitadas' }).click();
  await page.getByRole('radio', { name: '' }).click();
  await page.getByRole('radio', { name: '' }).click();
  await page.getByRole('radio', { name: '' }).click();
  await page.getByRole('button', { name: ' Actualizar' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Observadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones Aprobadas' }).click();
  await page.getByRole('radio', { name: 'Inscripciones en Revisión' }).click();
  await page.getByRole('tab', { name: ' Persona Jurídica' }).click();
  await page.getByRole('tab', { name: ' Persona Natural' }).click();
  await page.getByRole('button', { name: 'AM' }).click();
  await page.getByRole('button', { name: ' Cerrar Sesión' }).click();
});